name: Update Domain List and Create Release

on:
  schedule:
    - cron: '0 0 * * *'  # Выполнять раз в сутки (в полночь по UTC)
  workflow_dispatch:     # Позволяет запускать workflow вручную

jobs:
  update-and-release:
    runs-on: ubuntu-latest
    env:
      TARGET_IP: "80.90.186.12"  # Задайте нужный IP здесь
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download domain list
        run: |
          curl -sSL https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Russia/inside-raw.lst -o raw_domains.lst

      - name: Transform domain list
        run: |
          mkdir -p output
          awk -v ip="$TARGET_IP" '{print "||" $0 "^$dnsrewrite=" ip}' raw_domains.lst > output/processed_domains.txt

      - name: Commit and push to main branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          cp output/processed_domains.txt ./processed_domains.txt
          git add processed_domains.txt
          git commit -m "Update processed_domains.txt [Automated]" || echo "No changes to commit"
          git push origin main

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "release-${{ steps.date.outputs.date }}"
          name: "Daily Update - ${{ steps.date.outputs.date }}"
          body: "Daily update of processed domain list."
          files: output/processed_domains.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
